// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn_smJlNEhxKKfqKSoeVaqPXB0Lh_M-Ik',
    appId: '1:353311343572:web:6043c8135d21182e',
    messagingSenderId: '353311343572',
    projectId: 'prova-53d3e',
    authDomain: 'prova-53d3e.firebaseapp.com',
    databaseURL: 'https://prova-53d3e.firebaseio.com',
    storageBucket: 'prova-53d3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkTGPb1rVd8c8wC1yLyKqIIjCZ20zje60',
    appId: '1:353311343572:android:26d1021447b798617ecc41',
    messagingSenderId: '353311343572',
    projectId: 'prova-53d3e',
    databaseURL: 'https://prova-53d3e.firebaseio.com',
    storageBucket: 'prova-53d3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq83qqhSkzrdrcH6XSF9j7Lm03o4F75TI',
    appId: '1:353311343572:ios:843ef762d50475277ecc41',
    messagingSenderId: '353311343572',
    projectId: 'prova-53d3e',
    databaseURL: 'https://prova-53d3e.firebaseio.com',
    storageBucket: 'prova-53d3e.appspot.com',
    iosClientId: '353311343572-uldmkm8l6mja4h3u8n9m3s2fq9tefsmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.boilerplateAuthCrudFirestoreBloc',
  );
}
